// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://surfe.com",
            "email": "support@surfe.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contact/{id}": {
            "get": {
                "description": "Returns the basic information around the contact based on their ID",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["contacts"],
                "summary": "Get contact by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Contact"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enrichment/start": {
            "post": {
                "description": "Starts an enrichment process, taking the userID and additional optional payload",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["enrichment"],
                "summary": "Start an enrichment",
                "parameters": [
                    {
                        "description": "Enrichment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EnrichmentStartRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/EnrichmentStartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/enrichment/{id}": {
            "get": {
                "description": "Returns the status of the enrichment based on the ID",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["enrichment"],
                "summary": "Get enrichment status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enrichment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Enrichment"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/thirdparty/{full_name}": {
            "get": {
                "description": "Returns additional information about the user based on their full name",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["thirdparty"],
                "summary": "Get third-party information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full name (URL encoded)",
                        "name": "full_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ThirdPartyInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API",
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Contact": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "jobTitle": {
                    "type": "string"
                }
            }
        },
        "Enrichment": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": ["pending", "in_progress", "completed", "failed"]
                },
                "createdAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/EnrichmentResult"
                }
            }
        },
        "EnrichmentResult": {
            "type": "object",
            "properties": {
                "linkedInUrl": {
                    "type": "string"
                },
                "twitterUrl": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "experienceYears": {
                    "type": "integer"
                }
            }
        },
        "EnrichmentStartRequest": {
            "type": "object",
            "required": ["userId"],
            "properties": {
                "userId": {
                    "type": "string"
                },
                "options": {
                    "type": "object"
                }
            }
        },
        "EnrichmentStartResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "ThirdPartyInfo": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "linkedInUrl": {
                    "type": "string"
                },
                "twitterHandle": {
                    "type": "string"
                },
                "githubUsername": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "companies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Surfe Mock API",
	Description:      "A mock API for frontend interview purposes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
